---

- name: Converge
  hosts: all
  tasks:
    - name: Include role 'ansible-role-hashicorp' (package)
      include_role:
        name: ansible-role-hashicorp
      vars:
        hashicorp_product: "{{ item }}"
      loop:
        - terraform
        - vagrant
        - terraform
        - packer
        - consul
        - vault
        - nomad

    - name: Include role 'ansible-role-hashicorp' (binary)
      include_role:
        name: ansible-role-hashicorp
      vars:
        hashicorp_product: "{{ item }}"
        hashicorp_install_mode: binary
      loop:
        - terraform
        - vagrant
        - terraform
        - packer
        - consul
        - vault
        - nomad
